<a href="https://colab.research.google.com/github/ferdinano/Aprendizaje_automatico_2026/blob/main/Clase1/Ejercicios_de_Arrays_y_Matrices_con_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ejercicios de Arrays y Matrices con NumPy

In [7]:
## Ejercicio 1: Crear un array de 10 elementos con ceros.
import numpy as np
array_ceros = np.zeros(10)
print(array_ceros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
## Ejercicio 1: Crear un array de 10 elementos con ceros.
import numpy as np
array_dos = np.full(10, 0)
print(array_dos)

[0 0 0 0 0 0 0 0 0 0]


In [10]:
### Ejercicio 2: Genera un array con los números del 1 al 20.
array_num = np.arange(1, 21)
print(array_num)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
# Ejercicio 3: Crea un array con los números pares del 2 al 50.
array_par = np.arange(2, 51, 2)
print(array_par)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [16]:
# Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.
matriz_aleatoria = np.random.rand(4, 4)
print(matriz_aleatoria)


[[0.14268771 0.7675066  0.12713178 0.1517885 ]
 [0.41039282 0.54257798 0.10471198 0.83109215]
 [0.95279936 0.04082216 0.11072159 0.1737203 ]
 [0.43083073 0.93197635 0.86178441 0.37451618]]


In [17]:
# Ejercicio 6: Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].
suma_array = np.array ([1,2,3]) + np.array([4,5,6])
print(suma_array)

[5 7 9]


In [23]:
# Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.
matriz_1 = np.random.randint(1, 11, size=(3, 3))
matriz_2  = np.random.randint(1, 11, size=(3, 3))
multiplicacion_matriz = matriz_1 * matriz_2
print(matriz_1)
print(matriz_2)
print(multiplicacion_matriz)

[[ 9 10  9]
 [ 2 10  3]
 [ 7  1  7]]
[[ 5  3  6]
 [ 7  1 10]
 [ 1  5  5]]
[[45 30 54]
 [14 10 30]
 [ 7  5 35]]


In [27]:
# Ejercicio 8: Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.
array_aleatorio = np.random.randint(1, 101, size=15)
print(array_aleatorio)
print(np.max(array_aleatorio))
print(np.min(array_aleatorio))
print(np.mean(array_aleatorio))

[93 33 23 79 95 69  8 12 13 97 35  8 36 45 19]
97
8
44.333333333333336


In [29]:
# Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.
matriz_5x5 = np.arange(1, 26).reshape(5, 5)
print(matriz_5x5)
# extrae su diagonal
diagonal_matriz = np.diag(matriz_5x5)
print(diagonal_matriz)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  7 13 19 25]


In [34]:
# Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.
matriz_5 = np.random.randint(1, 11, size=(5, 5))
print(matriz_5)
diagonal_matriz_5 = np.diag(matriz_5)
print(diagonal_matriz_5)

[[ 4  4 10  1  8]
 [10  7  9  7  8]
 [ 4  1  7  6  4]
 [ 9  4  5  3  3]
 [ 4  6  2  4  9]]
[4 7 7 3 9]


In [36]:
# Ejercicio 10 : Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna
matriz_aleatoria_1 = np.random.randint(1, 21, size=(5, 5))
print(matriz_aleatoria_1)
# suma de cada fila
suma_filas = np.sum(matriz_aleatoria_1, axis=1)
print(suma_filas)
# Suma de cada columna
suma_columnas = np.sum(matriz_aleatoria_1, axis=0)
print(suma_columnas)

[[ 7 16  2 12 20]
 [19 20 10  1  1]
 [12 20  3 16  6]
 [ 9 13  2  4  4]
 [ 6  6  1  5 14]]
[57 51 57 32 32]
[53 75 18 38 45]
